In [1]:
import numpy as np

In [3]:
data = np.load("./out/A1/A1_SBM_K4_dense_splits_seed42.npz")
data.keys()

KeysView(NpzFile './out/A1/A1_SBM_K4_dense_splits_seed42.npz' with keys: train, val, test)

In [7]:
data["test"].shape

(10438, 2)

In [16]:
nodes = np.load("./out/A1/A1_SBM_K4_dense_nodes.npz")
nodes["positions"], nodes["blocks"]

(array([[0., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [0., 0.],
        [0., 1.],
        [1., 0.]]),
 array([2, 0, 0, ..., 2, 1, 0]))

In [24]:
nodes["positions"][:10]

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [17]:
nodes["positions"].shape, nodes["blocks"].shape

((5000, 2), (5000,))

In [15]:
nodes

NpzFile './out/A1/A1_SBM_K4_dense_nodes.npz' with keys: positions, blocks